# Generated by Django 3.0.2 on 2020-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=128)),
                ('Last_Name', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
